# -*- coding: utf-8 -*-
"""PC_1_Quimica_UNMSM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13oxjYvTC52kRtn7KbwOpTRy90CCBHnsL

$$\Large \textit{UNMSM | Química}$$
$$\large \textbf{PC Nº1 | Materia y clasificación}$$

_Profesor: Jesus Alvarado Huayhuaz_

Todas las indicaciones para la presentación de la práctica son explicadas en clase y brindadas en el material de enunciado de preguntas en formato PDF.

## Pregunta 1: Sobre el ABC de python (4 puntos)

Durante la semana de revisión del material "ABC de python", reflexiona sobre qué conceptos aprendiste con claridad y cuáles consideras los más desafiantes. A continuación resuelve los siguiente ejercicios, puedes ayudarte del material en http://bit.ly/3YKICSZ.
"""

# Imprime la versión de python que usas y las palabras reservadas de python para esa versión.

# Crea una matriz de 3x3 e imprime la suma de los elementos en su diagonal (traza).

# Guarda como variable la masa atómica de los elementos C, H y O, e imprime la masa molecular del etanol.

# Busca la temperatura de fusión en Celsius de 5 metales y guárdalos en una lista. Imprime las temperaturas en Kelvin

"""## Pregunta 2: Operaciones (4 puntos)

Escribe un programa que lea repetidamente elementos químicos en español hasta que el usuario introduzca “fin”. Una vez se haya introducido “fin”, muestra por pantalla (o sea imprime) el total de elementos ingresados. Si el usuario introduce cualquier otra cosa que no sea un elemento químico, detecta su fallo usando try y except, muestra un mensaje de error y pasa al siguiente elemento.
"""



"""# Pregunta 3: Conservación de la masa (4 puntos)

### Código necesario para generar la imagen
"""

!pip install faerun-notebook==0.1.5b0

import ipywidgets as widgets
from faerun_notebook import SmilesDrawer
from google.colab import output
output.enable_custom_widget_manager()

"""### Reacción química

Demuestra cómo se cumple la conservación de la masa en la siguiente reacción química. Sugerencia: hacer un balance estequiométrico y luego emplear la masa molecular de reactivos y productos.
"""

SmilesDrawer(value=[("Rxn", "C(C1C(C(C(C(O1)O)O)O)O)O.O=O>>C(=O)=O.O")], theme='dark', background="#1e1e1e", options={'scale': 1.25})

"""## Pregunta 4: Notación científica (4 puntos)

Imprime las siguientes operaciones según la notación científica:

(1) $1.321 \times 10^{-4} + 8.5 \times 10^{-2}$

(2) $1.71 \times 10^{3} - 2.01 \times 10^{2}\$

(3) $(7.4 \times 10^5)(7.2 \times 10^4)$

(4) $(7.4 \times 10^5)/(7.2 \times 10^4)$

## Pregunta 5: Método científico (4 puntos)

Artículo: https://bit.ly/3surZ1W
Leer el siguiente artículo y explica cómo es aplicado el método científico. Emplea como máximo 300 palabras.

Este archivo PDF contiene información sobre dos temas diferentes. El primero es el descubrimiento del LK-99, un material que en un principio se creyó superconductor, pero luego se descubrió que presentaba otras propiedades. El artículo explica que los investigadores utilizaron imágenes de rayos X de precisión y otras técnicas para comprender mejor el material y aclarar sus propiedades reales. El artículo también menciona que el material sigue presentando propiedades interesantes que han captado la atención de científicos y público por igual.

El segundo tema tratado en el archivo PDF son los progresos realizados en la erradicación del poliovirus salvaje en Afganistán y Pakistán. El artículo explica que la Organización Mundial de la Salud (OMS) ha declarado que estos dos países están más cerca que nunca de erradicar el virus, a pesar de las críticas anteriores a la labor de erradicación. El artículo señala que el éxito de los programas de erradicación en estos países dependerá de su capacidad para superar los persistentes retos sociales y políticos.

En general, este archivo PDF ofrece información interesante sobre los descubrimientos científicos y los esfuerzos de salud pública. Destaca la importancia de las técnicas de imagen de precisión para comprender los materiales y los retos que plantea la erradicación de enfermedades.  El método científico es un enfoque sistemático de la investigación científica que consta de varios pasos. Estos pasos suelen incluir:

1. Observación: Los científicos observan un fenómeno o problema que quieren investigar.

2. Hipótesis: Los científicos desarrollan una explicación comprobable del fenómeno o problema, denominada hipótesis.

3. Predicción: Los científicos hacen predicciones sobre lo que esperan observar si su hipótesis es correcta.

4. Experimentación: Los científicos diseñan y realizan experimentos para comprobar sus hipótesis y predicciones.

5.Análisis de datos: Los científicos analizan los datos que recogen de sus experimentos para determinar si sus hipótesis se apoyan o no.

6.  Conclusión: Los científicos sacan conclusiones basadas en el análisis de sus datos y determinan si su hipótesis se apoya o no.

7. Comunicación: Los científicos comunican sus hallazgos a la comunidad científica a través de publicaciones, presentaciones y otros medios.

El método científico es un proceso iterativo, lo que significa que los científicos pueden repetir pasos o modificar su enfoque en función de sus hallazgos.
"""